### ISSUE TITLE
truncated vcf record

### ISSUE THREAD

**Issue by tobsecret** [rvalieris/signeR#15] opened 2019-07-13 21:01 UTC
signeR gets tripped up in makeGenCountMatrixFromVcf because it thinks a VCF record is truncated.
code:
[makeGenCountMatrixFromVcf.R.txt](https://github.com/rvalieris/signeR/files/3389224/makeGenCountMatrixFromVcf.R.txt)

Error:
```
  Error in value[[3L]](cond) : 
     record 816 (Pv_Sal1_chr13:0-2) was truncated
    file: PlasmoDB-10.0_PvivaxSal1_Genome_clean.fasta
  Calls: genCountMatrixFromVcf ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
  In addition: Warning message:
  In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
    GRanges object contains 1 out-of-bound range located on sequence
    Pv_Sal1_chr13. Note that ranges located on a sequence whose length is
    unknown (NA) or on a circular sequence are not considered out-of-bound
    (use seqlengths() and isCircular() to get the lengths and circularity
    flags of the underlying sequences). You can use trim() to trim these
    ranges. See ?`trim,GenomicRanges-method` for more information.
  Execution halted
```
This is odd, because gatk ValidateVariants thinks the file is totally fine:
[gatk_ValidateVariants_from_vcf_that_signeR_thinks_are_truncated.txt](https://github.com/rvalieris/signeR/files/3389235/gatk_ValidateVariants_from_vcf_that_signeR_thinks_are_truncated.txt)

The two lines from the VCF that could be it are the following (I never remember if the indexing is 0 or 1 based), I think it's the second line: 
[2lines_from_vcf_that_signeR_thinks_are_truncated.vcf.txt](https://github.com/rvalieris/signeR/files/3389219/2lines_from_vcf_that_signeR_thinks_are_truncated.vcf.txt)
Thought it might have something to do  with https://github.com/Bioconductor/VariantAnnotation/issues/8 but even with a higher version of VariantAnnotation (1.28.13), this issue persists.

I'm using a slightly older version of signeR (1.8.0), do you think that would be the issue? 
Don't think it's https://github.com/rvalieris/signeR/issues/11 because the genotypes are not phased. 
Been having a hard time building a container with a higher version of signeR in it and all the other programs  that I need, that works, so hence why I haven't been using the latest version yet.

**Comment by rvalieris** [comment] 2019-07-15 15:03
>GRanges object contains 1 out-of-bound range located on sequence Pv_Sal1_chr13.

could this warning be related to the error ?

can you reproduce the issue with a smaller vcf ? just the header + these 2 lines maybe ?

if this is really an issue with VariantAnnotator there's not much I can do, but I could help look into it with an example vcf with the error.

**Comment by tobsecret** [comment] 2019-07-15 17:51
In the following, after downloading, remove the .txt extension from every filename.
I have made a copy of the supposedly truncated 2 lines:
[2lines_from_vcf_that_signeR_thinks_are_truncated.vcf.txt](https://github.com/rvalieris/signeR/files/3393496/2lines_from_vcf_that_signeR_thinks_are_truncated.vcf.txt)
reference fasta (gzipped bc github upload limits)
[PlasmoDB-10.0_PvivaxSal1_Genome.fasta.gz.txt](https://github.com/rvalieris/signeR/files/3393490/PlasmoDB-10.0_PvivaxSal1_Genome.fasta.gz.txt)

Here is the reference index:
[PlasmoDB-10.0_PvivaxSal1_Genome.fasta.fai.txt](https://github.com/rvalieris/signeR/files/3393479/PlasmoDB-10.0_PvivaxSal1_Genome.fasta.fai.txt)
[2lines_from_vcf_that_signeR_thinks_are_truncated.vcf.txt](https://github.com/rvalieris/signeR/files/3393480/2lines_from_vcf_that_signeR_thinks_are_truncated.vcf.txt)
The script that reproduces the error: 
[makeGenCountMatrixFromVcf_example.R.txt](https://github.com/rvalieris/signeR/files/3393481/makeGenCountMatrixFromVcf_example.R.txt)

Some relevant package versions: 
* R version 3.5.1 
* signeR_1.8.0
* VariantAnnotation_1.28.13
* Biostrings_2.50.2
* GenomicRanges_1.34.0

**Comment by rvalieris** [comment] 2019-07-15 19:22
alright I found the issue.

to generate the counts in the 96 format, we need to pick the bases before and after each mutation on the genome, the problem is when there is a mutation on the first base of the chromosome, as is the case here.
this mutation can't be counted in this format, in a future version I will add a filter for these and a warning.

for now, you can filter these mutations out manually. this should do the trick:
`vcfobj = vcfobj[granges(vcfobj)@ranges@start>1]`
also apply a similar filter if there are mutations in the last base of chromosomes.

**Comment by tobsecret** [comment] 2019-07-15 19:34
Oh no :man_facepalming:  I should have thought of that! That makes total sense :sweat_smile: 
Thanks so much for all the support!

**Comment by tobsecret** [comment] 2019-07-15 19:38
Probably would need a filter for the other end of the chromosome as well. How would one do that?

**Comment by rvalieris** [comment] 2019-07-15 20:32
not sure whats the best way of doing this yet, but something like this:

```
gr = granges(vcfobj)
f1 = GRanges(seqnames=seqinfo(gr)@seqnames, ranges=IRanges(start=1,end=1))
f2 = GRanges(seqnames=seqinfo(gr)@seqnames, ranges=IRanges(start=seqinfo(gr)@seqlengths,end=seqinfo(gr)@seqlengths))

gr = subsetByOverlaps(gr, f1, invert=T)
gr = subsetByOverlaps(gr, f2, invert=T)

vcfobj = vcfobj[granges(vcfobj)==gr]
```

**Comment by tobsecret** [comment] 2019-07-15 23:21
Thanks! I will test that out, too and see if it runs.

**Comment by rvalieris** [comment] 2019-07-17 14:30
for the record, this is the filter I will be adding later to signer. it mostly does the same thing, but it checks the genome to ignore possible circular chromosomes, these don't have edges and don't need to have any mutations filtered.

```R
# remove mutations on chrom edges
# but not if the chrom is circular
si = as.data.frame(seqinfo(bsgenome))
si = si[(is.na(si$isCircular) | si$isCircular==FALSE),]
si = GRanges(seqinfo(bsgenome)[rownames(si)])
if(length(subsetByOverlaps(vcfobj, si, type='start')) > 0 ||
    length(subsetByOverlaps(vcfobj, si, type='end')) > 0) {
    warning("Mutations on the edge of chromosomes will be ignored.")
    vcfobj = subsetByOverlaps(vcfobj, si, type='start', invert=T)
    vcfobj = subsetByOverlaps(vcfobj, si, type='end', invert=T)
}
```

**Comment by tobsecret** [comment] 2019-07-17 15:52
Good to know! :pray:

**Comment by rvalieris** [comment] 2019-07-18 20:02
fixed on master.

**Closed as completed by rvalieris** 2019-07-18 20:02 UTC
Labels: bug
